"""
Citation Validator and Provenance Resolver for Archival RAG.
Verifies every citation [n] generated by the LLM against retrieved chunks,
checks quotation fidelity against chunk text, builds verified citation cards,
and reconstructs the full archival provenance chain:
chunk -> OCR page -> OCR version -> document version -> document -> source.
"""

import re
import logging
from typing import List, Dict, Any, Tuple, Set

logger = logging.getLogger("archive.rag.citation_validator")

class CitationValidator:
    """
    Validates in-text citations and maps them directly to archival records.
    """

    CITATION_PATTERN = re.compile(r'\[(?:Source\s+)?(\d+)\]', re.IGNORECASE)
    QUOTATION_PATTERN = re.compile(r'"([^"]{4,200})"\s*\[(?:Source\s+)?(\d+)\]', re.IGNORECASE)

    def validate_and_resolve(
        self,
        answer_text: str,
        source_map: Dict[int, Dict[str, Any]]
    ) -> Dict[str, Any]:
        """
        Validates LLM answer text against the available source_map.

        Returns:
            Dict containing:
                - is_grounded: bool
                - validation_status: str ("FULLY_GROUNDED" | "PARTIALLY_GROUNDED" | "UNGROUNDED" | "NO_CITATIONS")
                - citations: List[Dict[str, Any]] (CitationCards)
                - cited_source_indices: List[int]
                - invalid_citations: List[int]
                - quotation_checks: List[Dict[str, Any]]
                - sanitized_answer: str
        """
        if not answer_text or not answer_text.strip():
            return {
                "is_grounded": False,
                "validation_status": "EMPTY_ANSWER",
                "citations": [],
                "cited_source_indices": [],
                "invalid_citations": [],
                "quotation_checks": [],
                "sanitized_answer": ""
            }

        # 1. Extract all citation indices [n]
        found_matches = self.CITATION_PATTERN.findall(answer_text)
        found_indices = [int(m) for m in found_matches]
        unique_indices = sorted(list(set(found_indices)))

        valid_indices: List[int] = []
        invalid_indices: List[int] = []

        for idx in unique_indices:
            if idx in source_map:
                valid_indices.append(idx)
            else:
                invalid_indices.append(idx)

        # 2. Quotation fidelity checks
        quotation_checks = []
        for quote_text, src_str in self.QUOTATION_PATTERN.findall(answer_text):
            src_idx = int(src_str)
            check_record = {
                "quote": quote_text,
                "source_index": src_idx,
                "matched": False,
                "reason": "Source not in context"
            }
            if src_idx in source_map:
                chunk_content = source_map[src_idx].get("chunk_text", "")
                # Case-insensitive substring check, normalized whitespace
                norm_quote = " ".join(quote_text.lower().split())
                norm_chunk = " ".join(chunk_content.lower().split())
                if norm_quote in norm_chunk:
                    check_record["matched"] = True
                    check_record["reason"] = "Verbatim match in source text"
                else:
                    check_record["matched"] = False
                    check_record["reason"] = "Quotation does not match retrieved chunk text"
            quotation_checks.append(check_record)

        # 3. Build Citation Cards for all valid indices
        citation_cards: List[Dict[str, Any]] = []
        for idx in valid_indices:
            src = source_map[idx]
            chunk_id = src.get("chunk_id")
            doc_id = src.get("document_id")
            doc_title = src.get("document_title")
            archive_id = src.get("archive_id")
            page_no = src.get("page_number")
            folio_no = src.get("folio_number")
            doc_version_id = src.get("document_version_id")
            ocr_page_id = src.get("ocr_page_id")
            ocr_version_id = src.get("ocr_text_version_id")
            layer = src.get("transcription_layer") or "UNKNOWN"
            is_verified = src.get("is_verified", False)
            raw_chunk_text = src.get("chunk_text", "")

            # Construct full chain representation
            provenance_chain = {
                "chunk_id": chunk_id,
                "ocr_page_id": ocr_page_id,
                "ocr_text_version_id": ocr_version_id,
                "document_version_id": doc_version_id,
                "document_id": doc_id,
                "archive_id": archive_id,
                "layer": layer,
                "is_verified": is_verified,
                "chain_description": (
                    f"Chunk #{chunk_id} -> "
                    f"OCR Page #{ocr_page_id or 'N/A'} -> "
                    f"OCR Text Version #{ocr_version_id or 'N/A'} -> "
                    f"Doc Version #{doc_version_id or 'N/A'} -> "
                    f"Document #{doc_id} ({archive_id})"
                )
            }

            snippet = raw_chunk_text[:280].strip() + ("..." if len(raw_chunk_text) > 280 else "")

            citation_cards.append({
                "source_index": idx,
                "chunk_id": chunk_id,
                "document_id": doc_id,
                "archive_id": archive_id,
                "document_title": doc_title,
                "creator": src.get("creator"),
                "year": src.get("year"),
                "page_number": page_no,
                "folio_number": folio_no,
                "transcription_layer": layer,
                "is_verified": is_verified,
                "citation_label": src.get("citation"),
                "snippet": snippet,
                "provenance_chain": provenance_chain
            })

        # 4. Determine grounding status
        if not unique_indices:
            # Check if this is an explicit refusal / no-evidence answer
            if "not contain sufficient evidence" in answer_text.lower() or "no archival evidence" in answer_text.lower() or "insufficient" in answer_text.lower():
                status = "EVIDENCE_INSUFFICIENT"
                is_grounded = False  # Legitimate refusal due to lack of evidence
            else:
                status = "NO_CITATIONS"
                is_grounded = False
        elif invalid_indices and not valid_indices:
            status = "UNGROUNDED"
            is_grounded = False
        elif invalid_indices and valid_indices:
            status = "PARTIALLY_GROUNDED"
            is_grounded = False  # Contains hallucinated citation brackets
        else:
            status = "FULLY_GROUNDED"
            is_grounded = True

        # Normalize [Source n] to [n] in final output
        clean_text = self.CITATION_PATTERN.sub(r'[\1]', answer_text)

        return {
            "is_grounded": is_grounded,
            "validation_status": status,
            "citations": citation_cards,
            "cited_source_indices": valid_indices,
            "invalid_citations": invalid_indices,
            "quotation_checks": quotation_checks,
            "sanitized_answer": clean_text
        }
