"""phase3_ocr_digitization_models

Revision ID: 6a6aa00d2010
Revises: 2136ed324b71
Create Date: 2026-09-21 12:32:47.519786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a6aa00d2010'
down_revision: Union[str, Sequence[str], None] = '2136ed324b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('engine_version', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_config', sa.Text(), nullable=True),
    sa.Column('preprocessing_config', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('processed_pages', sa.Integer(), nullable=True),
    sa.Column('failed_pages', sa.Integer(), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_jobs_document_id'), 'ocr_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_ocr_jobs_id'), 'ocr_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_ocr_jobs_status'), 'ocr_jobs', ['status'], unique=False)
    op.create_table('ocr_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocr_job_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('dpi', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('confidence_category', sa.String(length=20), nullable=True),
    sa.Column('is_low_confidence', sa.Boolean(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('image_derivative_path', sa.String(length=500), nullable=True),
    sa.Column('original_page_image_path', sa.String(length=500), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ocr_job_id'], ['ocr_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_pages_id'), 'ocr_pages', ['id'], unique=False)
    op.create_index(op.f('ix_ocr_pages_ocr_job_id'), 'ocr_pages', ['ocr_job_id'], unique=False)
    op.create_index(op.f('ix_ocr_pages_status'), 'ocr_pages', ['status'], unique=False)
    op.create_table('ocr_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocr_page_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('block_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ocr_page_id'], ['ocr_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_blocks_id'), 'ocr_blocks', ['id'], unique=False)
    op.create_index(op.f('ix_ocr_blocks_ocr_page_id'), 'ocr_blocks', ['ocr_page_id'], unique=False)
    op.create_table('ocr_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocr_page_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('corrected_text', sa.Text(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ocr_page_id'], ['ocr_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_reviews_id'), 'ocr_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_ocr_reviews_ocr_page_id'), 'ocr_reviews', ['ocr_page_id'], unique=False)
    op.create_table('ocr_text_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocr_page_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ocr_page_id'], ['ocr_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_text_versions_id'), 'ocr_text_versions', ['id'], unique=False)
    op.create_index(op.f('ix_ocr_text_versions_ocr_page_id'), 'ocr_text_versions', ['ocr_page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ocr_text_versions_ocr_page_id'), table_name='ocr_text_versions')
    op.drop_index(op.f('ix_ocr_text_versions_id'), table_name='ocr_text_versions')
    op.drop_table('ocr_text_versions')
    op.drop_index(op.f('ix_ocr_reviews_ocr_page_id'), table_name='ocr_reviews')
    op.drop_index(op.f('ix_ocr_reviews_id'), table_name='ocr_reviews')
    op.drop_table('ocr_reviews')
    op.drop_index(op.f('ix_ocr_blocks_ocr_page_id'), table_name='ocr_blocks')
    op.drop_index(op.f('ix_ocr_blocks_id'), table_name='ocr_blocks')
    op.drop_table('ocr_blocks')
    op.drop_index(op.f('ix_ocr_pages_status'), table_name='ocr_pages')
    op.drop_index(op.f('ix_ocr_pages_ocr_job_id'), table_name='ocr_pages')
    op.drop_index(op.f('ix_ocr_pages_id'), table_name='ocr_pages')
    op.drop_table('ocr_pages')
    op.drop_index(op.f('ix_ocr_jobs_status'), table_name='ocr_jobs')
    op.drop_index(op.f('ix_ocr_jobs_id'), table_name='ocr_jobs')
    op.drop_index(op.f('ix_ocr_jobs_document_id'), table_name='ocr_jobs')
    op.drop_table('ocr_jobs')
    # ### end Alembic commands ###
