"""phase4_search_indexing_models

Revision ID: 715dcf202576
Revises: 6a6aa00d2010
Create Date: 2026-09-21 13:04:46.464149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '715dcf202576'
down_revision: Union[str, Sequence[str], None] = '6a6aa00d2010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_index_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('indexed_chunks', sa.Integer(), nullable=True),
    sa.Column('failed_chunks', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_dim', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_index_jobs_document_id'), 'search_index_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_search_index_jobs_id'), 'search_index_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_search_index_jobs_status'), 'search_index_jobs', ['status'], unique=False)
    op.create_table('search_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('document_version_id', sa.Integer(), nullable=True),
    sa.Column('ocr_text_version_id', sa.Integer(), nullable=True),
    sa.Column('ocr_page_id', sa.Integer(), nullable=True),
    sa.Column('ocr_block_id', sa.Integer(), nullable=True),
    sa.Column('chunk_sequence', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('folio_number', sa.String(length=50), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding_vector', sa.LargeBinary(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_version', sa.String(length=50), nullable=True),
    sa.Column('embedding_dim', sa.Integer(), nullable=True),
    sa.Column('is_normalized', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('transcription_layer', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ocr_block_id'], ['ocr_blocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ocr_page_id'], ['ocr_pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ocr_text_version_id'], ['ocr_text_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_chunks_content_hash'), 'search_chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_search_chunks_document_id'), 'search_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_search_chunks_id'), 'search_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_search_chunks_is_verified'), 'search_chunks', ['is_verified'], unique=False)
    op.create_index(op.f('ix_search_chunks_status'), 'search_chunks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_chunks_status'), table_name='search_chunks')
    op.drop_index(op.f('ix_search_chunks_is_verified'), table_name='search_chunks')
    op.drop_index(op.f('ix_search_chunks_id'), table_name='search_chunks')
    op.drop_index(op.f('ix_search_chunks_document_id'), table_name='search_chunks')
    op.drop_index(op.f('ix_search_chunks_content_hash'), table_name='search_chunks')
    op.drop_table('search_chunks')
    op.drop_index(op.f('ix_search_index_jobs_status'), table_name='search_index_jobs')
    op.drop_index(op.f('ix_search_index_jobs_id'), table_name='search_index_jobs')
    op.drop_index(op.f('ix_search_index_jobs_document_id'), table_name='search_index_jobs')
    op.drop_table('search_index_jobs')
    # ### end Alembic commands ###
